import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Display, Inter } from "next/font/google";
import { headers } from "next/headers";
import Header from "@/components/layout/header/header";
import { LenisProvider } from "@/components/layout/lenis-provider";
import "./style.scss";

import "./globals.css";
import Footer from "@/components/sections/global/footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    style: ["normal", "italic"],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    style: ["normal"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
    variable: "--font-dm-serif",
    subsets: ["latin"],
    weight: "400",
    style: ["normal", "italic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = (await headers()).get("x-locale") ?? "en";
    const isRtl = locale === "ar-om";
    //dir={isRtl ? "rtl" : "ltr"} 
	
    return (
        <html lang={locale} className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${dmSerifDisplay.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col overflow-x-hidden">
                <LenisProvider>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </LenisProvider>
            </body>
        </html>
    );
}
