import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Display, Inter } from "next/font/google";
import Header from "@/components/layout/header/header";
import "./style.scss";

import "./globals.css";
import Footer from "@/components/sections/global/footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
    variable: "--font-dm-serif",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${dmSerifDisplay.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col overflow-x-hidden">
                <Header />
                {children}
                <Footer />
                {/* <script src="./js/jquery.min.js"></script>
                <script src="./js/gsap.min.js"></script>
                <script src="./js/scroll-trigger.min.js"></script>
                <script src="./js/splitText.min.js"></script>
                <script src="./js/tween-max.min.js"></script>
                <script src="./js/gsap-init.js"></script> */}
            </body>
        </html>
    );
}
